replicaCount: 2
namespace: application
image:
  repository: ghcr.io/pcy06/hanowl.com
  pullPolicy: IfNotPresent
  tag: "edc3be29817dacfbb408ee92d11c2bfcb5e465f6"
imagePullSecrets: [{"name": "ghcr-pcy06"}]
podAnnotations: {}
podLabels: {}
service:
  type: ClusterIP
ingress:
  enabled: true
  className: "nginx"
  ingressDomain: "recruit.hanum.us"
  annotations: {}
  tls:
    enabled: true
    certManagerIssuer: "letsencrypt-prod"
    secretName: "hanum-recruit-tls"
