replicaCount: 2
namespace: application
image:
  repository: ghcr.io/pcy06/hanowl.com
  pullPolicy: IfNotPresent
  tag: "e431f8358c4afbfdd7ea8ea392e7a983808a497c"
imagePullSecrets: [{"name": "ghcr-pcy06"}]
podAnnotations: {}
podLabels: {}
service:
  type: ClusterIP
ingress:
  enabled: true
  className: "nginx"
  ingressDomain: "recruit.hanum.us"
  annotations: {}
  tls:
    enabled: true
    certManagerIssuer: "letsencrypt-prod"
    secretName: "hanum-recruit-tls"
